### ISSUE TITLE
_propertyMap empty

### ISSUE THREAD

**Issue by edneypitta** [garvincasimir/csharp-datatables-parser#15]
For some reason my _propertyMap is empty, then an exception is thrown when I call Parse() method on the following line:

var firstProp = Expression.Property(paramExpr, _propertyMap.First().Value.Property);

Could you fix it, please?

Thanks.

**Comment by garvincasimir** [comment]
@edneypitta Please inspect your HttpContext Request property to ensure the presence of the Datatables ajax parameters. Can you paste them in here? Those related to datatables that is.

Also, if you are using v1.1x you need to enable legacy mode for ajax options:

    $.fn.dataTable.ext.legacy.ajax = true;

I opted to remain with the legacy option because it means the library can support 1.9 and 1.10 clients. Once this option becomes deprecated I will switch over to the new parameters. I have been using this library with version 1.10 for a very long time now without problems.
